services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      # Sync source code for hot reload
      - .:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
